(()=>{
  const frame=document.getElementById('app');
  if(!frame)return;
  let doc=null,observer=null;
  const int=n=>Math.round(Number(n)||0).toLocaleString('ja-JP');
  const css=`
.ui-context{margin-left:5px;color:#8396aa;font-size:.62em;font-weight:700;letter-spacing:.08em;white-space:nowrap}
.compact-score-label{font-size:0!important}.compact-score-label::before{content:'得点';font-size:9px}.compact-score-label::after{content:attr(data-context);margin-left:4px;color:#8396aa;font-size:6px;font-weight:700;letter-spacing:.08em}
#set-summary{display:none!important}.selection-main-row{display:flex;align-items:baseline;gap:7px;margin:1px 0 5px;min-width:0}.selection-stage{margin:0;color:#edf4fb;font-size:12px;font-weight:800;letter-spacing:.05em;line-height:1.15;white-space:nowrap}.selection-main-row h2{margin:0!important;font-size:12px!important;line-height:1.2!important;font-weight:650!important;white-space:nowrap}
#selection>.overlay-stage,#normal-selection>.overlay-stage,#second-set-selection>.overlay-stage{margin-bottom:2px!important;color:#e8d089!important;font-size:8.5px!important;letter-spacing:.13em!important}
.overlay .choices .choice{height:56px!important;min-height:56px!important;padding:7px 8px!important;overflow:hidden!important;border-radius:8px!important}.overlay .choices .choice strong{font-size:10.5px!important;line-height:1.2!important;margin:0!important}.overlay .choices .choice span{font-size:7.8px!important;line-height:1.3!important}
#choices .choice,#second-set-choices .choice{background:#5b4d20!important;border-color:#bda35b!important;box-shadow:inset 0 1px 0 rgba(255,232,155,.2)!important}#choices .choice strong,#second-set-choices .choice strong{color:#ffe89b!important}#choices .choice span,#second-set-choices .choice span{color:#cdbf8f!important}#choices .choice em,#second-set-choices .choice em{display:none!important}
#normal-choices .choice.ui-normal-choice{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;column-gap:8px!important;row-gap:3px!important;align-items:baseline!important}#normal-choices .choice.ui-normal-choice strong{grid-column:1;grid-row:1;min-width:0;margin:0!important;white-space:normal}#normal-choices .choice-stack{grid-column:2;grid-row:1;color:#6f8193!important;font-size:7.8px!important;font-weight:600!important;text-align:right;white-space:nowrap}#normal-choices .choice-desc{grid-column:1/-1;grid-row:2;color:#91a2b4!important;font-size:7.8px!important;line-height:1.3}
.brand{font-size:11px!important;font-weight:800!important;letter-spacing:.08em!important;color:#94d5bd!important;opacity:1!important;text-transform:none!important;text-align:right!important}
.bottom-runtime-actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important;padding-top:9px!important}.bottom-runtime-actions button,.bottom-runtime-actions #back,.bottom-runtime-actions #new-run{box-sizing:border-box!important;width:100%!important;min-width:0!important;height:34px!important;min-height:34px!important;max-height:34px!important;margin:0!important;padding:0 9px!important;border:1px solid #40566f!important;border-radius:999px!important;background:#152335!important;color:#cdd9e6!important;box-shadow:none!important;font-size:10px!important;font-weight:500!important;line-height:32px!important;order:initial!important;appearance:none!important;-webkit-appearance:none!important}.bottom-runtime-actions #back[hidden]+#new-run{grid-column:1/-1}
.board-shell{position:relative!important}.legacy-result-panel.result-overlay-panel{position:absolute!important;inset:8px!important;z-index:80!important;display:flex!important;align-items:center!important;justify-content:center!important;margin:0!important;padding:8px!important;border:0!important;border-radius:12px!important;background:rgba(3,8,13,.42)!important;backdrop-filter:blur(1.6px);-webkit-backdrop-filter:blur(1.6px)}.legacy-result-panel.result-overlay-panel[hidden]{display:none!important}.legacy-result-panel.result-overlay-panel .result-card{width:min(100%,420px);max-height:100%;overflow:auto;padding:11px 12px;border:1px solid var(--line);border-radius:12px;background:rgba(13,22,32,.96);box-shadow:0 16px 40px rgba(0,0,0,.35)}.legacy-result-panel.result-overlay-panel h2{margin:0 0 7px;font-size:17px;line-height:1.25}.legacy-result-panel.result-overlay-panel .result-score strong{font-size:30px}#replay{display:none!important}
#result-details.result-detail-groups{display:block!important;margin:7px 0 2px!important;font-size:9px!important}.result-detail-group{padding:8px 0 2px;border-top:1px solid rgba(93,117,141,.32)}.result-detail-group:first-child{border-top:0;padding-top:2px}.result-detail-group>h3{margin:0 0 6px;color:#edf4fb;font-size:11px;font-weight:800}.result-detail-sub{padding:6px 0 2px;border-top:1px solid rgba(93,117,141,.22)}.result-detail-sub:first-of-type{border-top:0;padding-top:0}.result-detail-sub>h4{margin:0 0 4px;color:#a9d8c8;font-size:9px;font-weight:750}.detail-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:baseline;padding:2px 0}.detail-row span{color:#8fa2b5}.detail-row strong{color:#e3edf6;font-weight:650;text-align:right;font-variant-numeric:tabular-nums}.stage-set-block{padding:5px 0 1px;border-top:1px solid rgba(93,117,141,.18)}.stage-set-block:first-of-type{border-top:0}.stage-set-head{display:flex;justify-content:space-between;align-items:baseline;margin:0 0 3px;color:#e8d089;font-size:8.5px;font-weight:750}.legacy-result-panel details[open]>summary{position:sticky;top:-1px;z-index:4;padding:5px 0;background:rgba(13,22,32,.98)}
#graph-detail-overlay{padding:5px!important;background:rgba(3,7,11,.42)!important}#graph-detail-overlay .graph-detail-card{width:min(96%,340px)!important;max-height:96%!important;height:auto!important;padding:7px!important;background:rgba(14,22,32,.94)!important;overflow:auto!important}#graph-detail-overlay .graph-detail-head{position:sticky!important;top:0!important;z-index:5!important;margin:-2px -2px 5px!important;padding:2px!important;background:rgba(14,22,32,.98)!important}#graph-detail-overlay #graph-detail-close{width:26px!important;height:26px!important;min-width:26px!important;min-height:26px!important;padding:0!important;line-height:24px!important}.graph-detail-table{width:100%;border-collapse:collapse;table-layout:fixed;font-variant-numeric:tabular-nums}.graph-detail-table th,.graph-detail-table td{padding:6px 3px;border-bottom:1px solid rgba(93,117,141,.22);text-align:right;font-size:8px;white-space:nowrap}.graph-detail-table th{color:#7f92a6;font-size:7px;font-weight:650}.graph-detail-table th:first-child,.graph-detail-table td:first-child{text-align:left}.graph-detail-table td:first-child{color:#e8d089;font-weight:700}.graph-detail-table td{color:#dbe6f0}.graph-detail-caption{margin:0 0 5px;color:#8195a9;font-size:7.5px}.graph-detail-empty{padding:14px 8px;color:#8fa2b5;font-size:9px;text-align:center}
@media(max-width:390px){.legacy-result-panel.result-overlay-panel{inset:6px!important;padding:6px!important}.legacy-result-panel.result-overlay-panel .result-card{padding:10px}.selection-stage{font-size:11.5px}.bottom-runtime-actions button,.bottom-runtime-actions #back,.bottom-runtime-actions #new-run{height:32px!important;min-height:32px!important;max-height:32px!important;line-height:30px!important}}
`;
  function label(d,el,text,ctx=''){if(!el)return;el.replaceChildren(d.createTextNode(text));if(ctx){const s=d.createElement('small');s.className='ui-context';s.textContent=ctx;el.append(s);}}
  function heading(d,section,kind,stage){if(!section)return;const kindEl=section.querySelector(':scope>.overlay-stage');if(kindEl)kindEl.textContent=kind;let row=section.querySelector(':scope>.selection-main-row');if(!row){row=d.createElement('div');row.className='selection-main-row';kindEl?.after(row);}let st=row.querySelector('.selection-stage');if(!st){st=d.createElement('div');st.className='selection-stage';row.append(st);}st.textContent='STAGE '+stage;let h=row.querySelector('h2')||section.querySelector(':scope>h2');if(h){row.append(h);h.textContent='能力を選択';}}
  function normalText(name,a,value){let display=name;if(a?.kind==='score'&&!/%/.test(display))display+=` +${Math.round(Number(value||0)*100)}%`;let desc='取得すると効果が加算される。';if(a?.kind==='score')desc=(name.replace(/得点アップ$/,'').trim()||'対象')+'に関する得点を増やす。';else if(/子HP/.test(name))desc='繁殖時に生まれる子のHPを増やす。';else if(/捕食時HP回復/.test(name))desc='捕食時のHP回復量を増やす。';else if(/草食回復/.test(name))desc='植物を食べたときのHP回復量を増やす。';else if(/活動植物生成/.test(name))desc='植物生成に必要な活動値を減らす。';else if(/一時投入/.test(name))desc='取得時に一度だけ個体を追加する。';return{display,desc};}
  function normalChoices(d,s){if(!s)return;d.querySelectorAll('#normal-choices .choice[data-ability]').forEach(btn=>{const id=btn.dataset.ability,a=s.engine.NORMAL_ABILITIES[id];if(!a)return;const n=(s.state.normalStacks[id]||0)+1,cap=s.engine.values.normalStackCap,t=normalText(a.name,a,s.engine.values.normal[id]);const sig=[id,n,t.display,t.desc].join('|');if(btn.dataset.v11===sig)return;let strong=btn.querySelector('strong');strong.textContent=t.display;let stack=btn.querySelector('.choice-stack');if(!stack){stack=d.createElement('span');stack.className='choice-stack';btn.append(stack);}stack.textContent=n+'/'+cap;let desc=btn.querySelector('.choice-desc');if(!desc){desc=d.createElement('span');desc.className='choice-desc';btn.append(desc);}desc.textContent=t.desc;btn.querySelectorAll(':scope>span:not(.choice-stack):not(.choice-desc)').forEach(x=>x.remove());btn.classList.add('ui-normal-choice');btn.dataset.v11=sig;});}
  function syncGold(d){const items=d.querySelectorAll('.ability-set .set-ability');if(items.length<2||items[1].classList.contains('empty'))return;const c=d.defaultView.getComputedStyle(items[0]);for(const [p,v] of [['background',c.background],['border-color',c.borderTopColor],['color',c.color],['box-shadow',c.boxShadow]])items[1].style.setProperty(p,v,'important');}
  const row=(d,p,k,v)=>{const x=d.createElement('div');x.className='detail-row';const a=d.createElement('span'),b=d.createElement('strong');a.textContent=k;b.textContent=v;x.append(a,b);p.append(x);};
  const sub=(d,p,title,rows)=>{const s=d.createElement('div');s.className='result-detail-sub';const h=d.createElement('h4');h.textContent=title;s.append(h);rows.forEach(([k,v])=>row(d,s,k,v));p.append(s);};
  const sum=(rs,k)=>rs.reduce((n,r)=>n+Number(r.events?.[k]||0),0),comp=(rs,k)=>rs.reduce((n,r)=>n+Number(r.score?.components?.[k]||0),0);
  function resultDetails(d,s){const root=d.getElementById('result-details');if(!root||!s?.runDone)return;const sig=s.results.length+':'+int(s.runScore());if(root.dataset.v11===sig&&root.querySelector('.result-detail-group'))return;root.dataset.v11=sig;root.className='result-detail-groups';root.replaceChildren();const rs=s.results,eco=d.createElement('section');eco.className='result-detail-group';eco.innerHTML='<h3>生態系</h3>';sub(d,eco,'循環',[['植物摂食',int(sum(rs,'plantEaten'))],['捕食',int(sum(rs,'herbEaten'))]]);sub(d,eco,'出生・死亡',[['草食出生',int(sum(rs,'herbBirths'))],['肉食出生',int(sum(rs,'carnBirths'))],['草食死亡',`自然 ${int(sum(rs,'herbNaturalDeaths'))} / 捕食 ${int(sum(rs,'herbEaten'))}`],['肉食死亡',int(sum(rs,'carnNaturalDeaths'))]]);root.append(eco);const sc=d.createElement('section');sc.className='result-detail-group';sc.innerHTML='<h3>得点</h3>';sub(d,sc,'内訳',[['植物摂食',int(comp(rs,'herbFeed'))],['捕食',int(comp(rs,'carnPred'))],['草食出生',int(comp(rs,'herbBirth'))],['肉食出生',int(comp(rs,'carnBirth'))],['草食生存',int(comp(rs,'herbSurvival'))],['肉食生存',int(comp(rs,'carnSurvival'))]]);const stage=d.createElement('div');stage.className='result-detail-sub';stage.innerHTML='<h4>STAGE別</h4>';for(let set=1;set<=2;set++){const block=d.createElement('div');block.className='stage-set-block';const rs2=rs.filter(r=>r.set===set),head=d.createElement('div');head.className='stage-set-head';head.innerHTML=`<span>SET ${set}</span><span>${int(rs2.reduce((n,r)=>n+Number(r.score?.total||0),0))}</span>`;block.append(head);rs2.forEach(r=>row(d,block,'STAGE '+r.stage,int(r.score?.total||0)));stage.append(block);}sc.append(stage);root.append(sc);}
  function graphDetails(d,s){const root=d.getElementById('graph-detail-content'),overlay=d.getElementById('graph-detail-overlay');if(!root||!s||overlay?.hidden)return;const set=s.runDone?2:Number(s.set||1),rs=s.results.filter(r=>Number(r.set)===set),sig=set+':'+rs.map(r=>[r.stage,r.score?.total,r.counts?.plants,r.counts?.herbs,r.counts?.carns].join('/')).join('|');if(root.dataset.v11===sig&&root.querySelector('.graph-detail-table'))return;root.dataset.v11=sig;root.replaceChildren();if(!rs.length){root.innerHTML='<div class="graph-detail-empty">STAGE終了後に詳細を表示します。</div>';return;}const cap=d.createElement('p');cap.className='graph-detail-caption';cap.textContent=`SET ${set} · STAGE終了時`;const table=d.createElement('table');table.className='graph-detail-table';table.innerHTML='<thead><tr><th>STAGE</th><th>得点</th><th>植物</th><th>草食</th><th>肉食</th></tr></thead>';const body=d.createElement('tbody');rs.forEach(r=>{const tr=d.createElement('tr');[r.stage,int(r.score?.total||0),int(r.counts?.plants||0),int(r.counts?.herbs||0),int(r.counts?.carns||0)].forEach(v=>{const td=d.createElement('td');td.textContent=v;tr.append(td);});body.append(tr);});table.append(body);root.append(cap,table);}
  function apply(d,w){const s=w.__v1rSession,sel=d.getElementById('selection'),normal=d.getElementById('normal-selection'),second=d.getElementById('second-set-selection');if(sel){heading(d,sel,'SET ABILITY',1);sel.querySelector(':scope>.hint')?.setAttribute('hidden','');const lab=sel.querySelector('label[for="seed"]');if(lab)lab.textContent='seed';const b=sel.querySelector('#seed-form button');if(b)b.textContent='候補を表示';}if(normal){heading(d,normal,'NORMAL ABILITY',s?Math.min(6,Number(s.stage||0)+1):2);normal.querySelector(':scope>.hint')?.setAttribute('hidden','');normalChoices(d,s);}if(second){heading(d,second,'SET ABILITY',1);second.querySelectorAll(':scope>.hint').forEach(x=>x.hidden=true);const x=d.getElementById('set-summary');if(x){x.hidden=true;x.replaceChildren();}}const score=d.getElementById('score-label');if(score){score.classList.add('compact-score-label');score.dataset.context=s?'SET '+s.set:'';}graphDetails(d,s);const result=d.getElementById('result');if(result&&!result.hidden){const h=d.getElementById('result-heading');if(h)h.textContent='12 Stage 完了';label(d,d.getElementById('result-score-label'),'得点','TOTAL');const cards=d.querySelectorAll('.final-set-scores>div>span');label(d,cards[0],'得点','SET 1');label(d,cards[1],'得点','SET 2');const details=result.querySelector('details'),summary=details?.querySelector(':scope>summary');if(summary){summary.textContent=details.open?'詳細を閉じる':'詳細';if(!details.dataset.v11toggle){details.dataset.v11toggle='1';details.addEventListener('toggle',()=>summary.textContent=details.open?'詳細を閉じる':'詳細');}}const replay=d.getElementById('replay');if(replay)replay.hidden=true;resultDetails(d,s);}if(s?.runDone){const gh=d.getElementById('score-graph-heading'),gc=d.getElementById('graph-stage-count');if(gh)gh.textContent='SET 2 · 累計得点';if(gc)gc.textContent='6 / 6';}syncGold(d);}
  function install(){let d,w;try{d=frame.contentDocument;w=frame.contentWindow;}catch(_){return;}if(!d?.head||!d.querySelector('.board-shell'))return;if(doc!==d){doc=d;observer?.disconnect();const st=d.createElement('style');st.id='ui-v11-style';st.textContent=css;d.head.append(st);const board=d.querySelector('.board-shell'),result=d.getElementById('result');if(result&&!result.dataset.overlayInstalled){const card=d.createElement('div');card.className='result-card';while(result.firstChild)card.append(result.firstChild);result.append(card);result.classList.add('result-overlay-panel');board.append(result);result.dataset.overlayInstalled='1';}const score=d.getElementById('score-panel');if(score&&!score.dataset.keepVisible){score.dataset.keepVisible='1';const keep=()=>{if(w.__v1rSession?.runDone&&score.hidden)score.hidden=false;};new MutationObserver(keep).observe(score,{attributes:true,attributeFilter:['hidden']});keep();}const overlay=d.getElementById('graph-detail-overlay');if(overlay&&!overlay.dataset.v11close){overlay.dataset.v11close='1';overlay.addEventListener('click',e=>{if(e.target===overlay)d.getElementById('graph-detail-close')?.click();});}observer=new MutationObserver(()=>requestAnimationFrame(()=>apply(d,w)));observer.observe(d.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['hidden','class']});}apply(d,w);}
  frame.addEventListener('load',()=>{setTimeout(install,50);setTimeout(install,250);setTimeout(install,800)});const timer=setInterval(install,250);setTimeout(()=>clearInterval(timer),15000);
})();
